'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const prefix=fs.readFileSync('verification/smoke-test.js','utf8').split('const storage = new Map();')[0].replace('return {\n    elements,','return {\n    context,\n    elements,');
function game(storage=new Map()) { const o={require,Buffer,console,TextEncoder,TextDecoder,URL,Blob};vm.runInNewContext(prefix+'\nglobalThis.create=createHarness;',o);const g=o.create(storage);g.eval=s=>vm.runInNewContext(s,g.context);g.storage=storage;return g; }
function fixture(n=40) {const g=game();g.eval(`reiniciarNovaColonia();estado.populacaoColonia=${n};estado.idadesAdultosColonia=Array(${n}).fill(32);estado.quantidadeCasasColonia=Math.ceil(${n}/5);estado.etapaConstrucaoColonia=4;estado.tesouroColonia=20000;estado.mapaAtual='expansao';estado.mapaExpansaoComprado=true;estado.salvamentoAtivo=true;estado.revisaoColonia=versaoColonia;sincronizarFamiliasColonia();estado.economiaCidada=novaEconomiaCidada();estado.empregosColonia={...estado.empregosColonia,administracao:2,lavoura:Math.min(6,${n}-2),geral:Math.max(0,${n}-8)};atualizarCadastroCidada(true);`);return g;}
const plain=x=>JSON.parse(JSON.stringify(x));
function conserved(g,label='money conservation'){g.eval('observarContasCidada()');assert.equal(g.eval('auditoriaCidada().diferenca'),0,label);}
let groups=0;function test(name,fn){fn();groups++;console.log('PASS '+name);}
test('one real person per adult and child; stable names, jobs and addresses',()=>{const g=fixture(450);g.eval(`estado.quantidadeMilicianos=10;estado.quantidadeGuardas=10;estado.quantidadeSoldados=10;redistribuirTrabalhadoresColonia();atualizarCadastroCidada(true);`);const e=g.estado.economiaCidada;assert.equal(e.adultos.length,450);assert.equal(new Set(e.adultos).size,450);assert.equal(Object.values(e.pessoas).filter(p=>['milicia','guarda','soldado'].includes(p.emprego)).length,30);assert.equal(g.eval('salarioDevidoCidada()'),g.eval('microsCidada(folhaCivilColonia()+folhaSoldosColonia())'));assert.equal(e.casas.reduce((n,h)=>n+h.membros.length,0),450);assert.ok(e.casas.every(h=>h.membros.length<=5));const before=JSON.stringify(e.pessoas);g.eval('atualizarCadastroCidada(true)');assert.equal(JSON.stringify(e.pessoas),before);conserved(g);});
test('funded wages credit wallets rather than disappear; no tax on payroll',()=>{const g=fixture();const before=g.estado.tesouroColonia;g.eval('pagarSalariosCidada(estado.empregosColonia)');const e=g.estado.economiaCidada;assert.equal(g.eval('auditoriaCidada().carteiras'),(before-g.estado.tesouroColonia)*1e6);assert.equal(e.totais.salarios,10000000);assert.equal(e.totais.tributoVendasCidade,0);assert.ok(e.livro.filter(r=>r.tipo==='salario').every(r=>r.de==='cidade'));conserved(g);});
test('migration clerks receive public-service pay and troops are not double-booked',()=>{const g=fixture();g.eval('estado.quantidadeMilicianos=5;estado.quantidadeGuardas=2;estado.quantidadeAdministradoresMigracao=2;redistribuirTrabalhadoresColonia();atualizarCadastroCidada(true)');assert.equal(g.eval('estado.empregosColonia.migracao'),2);assert.equal(g.eval('Object.values(estado.economiaCidada.pessoas).filter(p=>p.emprego==="migracao").every(p=>p.salario===2000000)'),true);assert.equal(g.eval('Object.values(estado.empregosColonia).reduce((a,b)=>a+b,0)'),33);g.eval('pagarSalariosCidada(estado.empregosColonia)');conserved(g);});
test('partial payroll apportions real cash exactly and records unpaid claims',()=>{const g=fixture();g.estado.tesouroColonia=.03;g.eval('observarContasCidada();pagarSalariosCidada(estado.empregosColonia)');assert.equal(g.estado.tesouroColonia,0);assert.equal(g.eval('auditoriaCidada().carteiras'),30000);assert.equal(g.eval('auditoriaCidada().atrasados'),9970000);assert.ok(Object.values(g.estado.economiaCidada.pessoas).every(p=>p.saldo>=0));conserved(g);});
test('exact 9% and 1% taxes; producer proceeds and sub-cent clearing are distinct',()=>{const g=fixture();g.eval('pagarSalariosCidada(estado.empregosColonia);vendaCidada(estado.economiaCidada.pessoas[estado.economiaCidada.adultos[0]],200000,"alimento","uma ração");liquidarCompensacaoCidada()');const e=g.estado.economiaCidada;assert.equal(e.totais.vendasBase,200000);assert.equal(e.totais.tributoVendasCidade,18000);assert.equal(e.totais.tributoVendasPessoal,2000);assert.equal(e.compensacaoCidade,8000);assert.equal(e.compensacaoPessoal,2000);conserved(g);});
test('insufficient wallets do not deny available food or mint taxed sales',()=>{const g=fixture();g.eval('liquidarAlimentacaoCidada(40,40)');const e=g.estado.economiaCidada;assert.equal(e.ultimo.alimentoSocial,40);assert.equal(e.ultimo.alimentoPago,0);assert.equal(e.totais.vendasBase,0);assert.ok(Object.values(e.pessoas).every(p=>p.alimento===1));assert.equal(g.estado.tesouroColonia,20000);conserved(g);});
test('physical shortage is not hidden by money or charged as delivered food',()=>{const g=fixture();g.eval('pagarSalariosCidada(estado.empregosColonia);liquidarAlimentacaoCidada(20,40)');const e=g.estado.economiaCidada;assert.equal(e.ultimo.faltaFisica,20);assert.equal(e.ultimo.alimentoPago+e.ultimo.alimentoSocial,20);assert.ok(Object.values(e.pessoas).every(p=>p.alimento===.5));assert.equal(e.ultimo.imovel,0);conserved(g);});
test('house levy is once per occupied house, 90/10 receipt split, with poverty exemption',()=>{const g=fixture(10);g.eval('pagarSalariosCidada(estado.empregosColonia);liquidarAlimentacaoCidada(10,10)');const e=g.estado.economiaCidada;assert.equal(e.totais.imovelCidade,180000);assert.equal(e.totais.imovelPessoal,20000);assert.equal(e.casas.length,2);assert.ok(e.casas.every(h=>h.taxa===100000));g.eval('estado.quantidadeCasasColonia=3;atualizarCadastroCidada(true)');assert.equal(e.casas[2].membros.length,0);conserved(g);});
test('children retain identity and inheritance when becoming adults',()=>{const g=fixture();g.eval(`estado.criancasColonia=[{id:'child-test',idade:duracaoInfanciaColonia,familiaId:estado.familiasColonia[0].id}];atualizarCadastroCidada(true);`);const id=g.estado.economiaCidada.jovens['child-test'],name=g.estado.economiaCidada.pessoas[id].nome;g.eval('estado.escolaConstruida=true;estado.empregosColonia.professor=1;atualizarFamiliasColonia();atualizarCadastroCidada(true)');assert.ok(g.estado.economiaCidada.adultos.includes(id));assert.equal(g.estado.economiaCidada.pessoas[id].nome,name);assert.equal(g.estado.economiaCidada.jovens['child-test'],undefined);assert.equal(g.estado.economiaCidada.adultos.length,41);conserved(g);});
test('death transfers existing money without tax or repeated estates',()=>{const g=fixture();g.eval('pagarSalariosCidada(estado.empregosColonia)');const e=g.estado.economiaCidada,id=e.adultos[0],heir=e.adultos[1],amount=e.pessoas[id].saldo,before=e.pessoas[heir].saldo;g.eval(`falecerPessoaCidada(0,'test');estado.idadesAdultosColonia.splice(0,1);estado.populacaoColonia--;atualizarCadastroCidada(true);`);assert.equal(e.pessoas[id],undefined);assert.equal(e.pessoas[heir].saldo,before+amount);assert.equal(e.totais.tributoVendasCidade,0);assert.equal(e.falecidos.length,1);conserved(g);});
test('discretionary goods consume actual stock and can be disabled',()=>{const g=fixture(10);g.eval(`pagarSalariosCidada(estado.empregosColonia);pagarSalariosCidada(estado.empregosColonia);pagarSalariosCidada(estado.empregosColonia);estado.mercadoPublicoConstruido=true;estado.empregosColonia.feirante=1;estado.estoqueMercadorias=3;estado.economiaCidada.ciclo=10;comprasOpcionaisCidada();liquidarCompensacaoCidada();`);const e=g.estado.economiaCidada;assert.equal(g.estado.estoqueMercadorias,2);assert.equal(Object.values(e.pessoas).reduce((n,p)=>n+p.bens,0),1);const before=e.totais.vendasBase;g.eval('estado.economiaCidada.opcionais=false;estado.economiaCidada.ciclo+=10;comprasOpcionaisCidada()');assert.equal(e.totais.vendasBase,before);conserved(g);});
test('legacy savings start at zero; save roundtrip preserves every wallet and tax remainder',()=>{const g=fixture();g.eval('redistribuirTrabalhadoresColonia();atualizarCadastroCidada(true);pagarSalariosCidada(estado.empregosColonia);liquidarAlimentacaoCidada(40,40);salvarProgresso()');const before=plain(g.estado.economiaCidada);const b=game(new Map(g.storage));b.eval('atualizarCadastroCidada(true)');assert.deepEqual(plain(b.estado.economiaCidada),before);conserved(b);for(let n=0;n<4;n++){b.eval('salvarProgresso();carregarProgresso();atualizarCadastroCidada(true)');assert.deepEqual(plain(b.estado.economiaCidada),before);}});
test('malformed accounts are bounded and orphan cash is held, not duplicated',()=>{const g=fixture();const raw=plain(g.estado.economiaCidada);raw.pessoas['cid-999']={...raw.pessoas['cid-1'],id:'cid-999',saldo:7};raw.adultos.push('cid-1');raw.pessoas['cid-1'].saldo=-123;raw.jovens={};g.context.raw=raw;const fixed=g.eval('normalizarEconomiaCidada(raw)');assert.equal(fixed.pessoas['cid-1'].saldo,0);assert.equal(new Set(fixed.adultos).size,fixed.adultos.length);assert.equal(fixed.custodia,7);assert.equal(fixed.pessoas['cid-999'],undefined);});
test('renderer is read-only with the individual roster',()=>{const g=fixture();g.eval('limitarCameraExpansao();atualizarCadastroCidada(true)');const before=plain(g.estado);for(let i=0;i<15;i++){g.eval('desenhar()');g.resetDrawCalls();}assert.deepEqual(plain(g.estado),before);});
test('bounded journal and exact global money reconciliation over repeated cycles',()=>{const g=fixture(450);g.eval(`for(let c=0;c<30;c++){pagarSalariosCidada(estado.empregosColonia);liquidarAlimentacaoCidada(450,450);observarContasCidada();if(auditoriaCidada().diferenca!==0)throw new Error('Cycle '+c+' money mismatch');}`);assert.equal(g.estado.economiaCidada.ciclo,30);assert.ok(g.estado.economiaCidada.livro.length<=512);assert.ok(Object.values(g.estado.economiaCidada.pessoas).every(p=>p.movimentos.length<=8));g.eval('salvarProgresso()');const bytes=Buffer.byteLength([...g.storage.values()][0]||'');assert.ok(bytes<1500000,bytes+' byte save');console.log('ECONOMY_CAPACITY '+JSON.stringify({residents:450,cycles:30,saveBytes:bytes,ledgerEntries:g.estado.economiaCidada.livro.length,conservation:g.eval('auditoriaCidada().diferenca')}));conserved(g);});
test('private service principal reaches a real non-waged provider and both taxes reconcile',()=>{
  const g=fixture(10);g.eval('pagarSalariosCidada(estado.empregosColonia)');
  const e=g.estado.economiaCidada,buyer=e.pessoas[e.adultos[0]],seller=Object.values(e.pessoas).find(p=>p.emprego==='geral');
  const b=buyer.saldo,v=seller.saldo;g.context.buyer=buyer;g.context.seller=seller;
  assert.equal(g.eval('vendaCidada(buyer,500000,"servico","Lazer na feira",seller)'),true);g.eval('liquidarCompensacaoCidada()');
  assert.equal(buyer.saldo,b-550000);assert.equal(seller.saldo,v+500000);assert.equal(seller.salario,0);
  assert.equal(seller.rendaServicos,500000);assert.equal(seller.servicosPrestados,1);
  assert.equal(e.totais.tributoVendasCidade,45000);assert.equal(e.totais.tributoVendasPessoal,5000);assert.equal(e.totais.receitaProdutorMunicipal,0);
  const cash=g.eval('patrimonioContabilCidada()');assert.equal(g.eval('vendaCidada(buyer,500000,"servico","self",buyer)'),false);assert.equal(g.eval('patrimonioContabilCidada()'),cash);conserved(g);
});
test('wage arrears are funded above the town reserve and never charged twice',()=>{
  const g=fixture();g.estado.tesouroColonia=0;g.eval('observarContasCidada();pagarSalariosCidada(estado.empregosColonia)');
  assert.equal(g.eval('auditoriaCidada().atrasados'),10000000);assert.equal(g.eval('quitarAtrasadosCidada()'),false);
  g.estado.tesouroColonia=20000;g.eval('observarContasCidada()');assert.equal(g.eval('quitarAtrasadosCidada()'),true);
  assert.equal(g.eval('auditoriaCidada().atrasados'),0);assert.equal(g.estado.tesouroColonia,19990);assert.equal(g.eval('quitarAtrasadosCidada()'),false);conserved(g);
});
test('unclaimed estates preserve cash and salary claims separately',()=>{
  const g=fixture(1);g.eval('estado.empregosColonia={...estado.empregosColonia,administracao:1,lavoura:0,geral:0};atualizarCadastroCidada(true);pagarSalariosCidada(estado.empregosColonia);estado.tesouroColonia=0;observarContasCidada();pagarSalariosCidada(estado.empregosColonia);');
  const before=g.eval('auditoriaCidada()');g.eval("falecerPessoaCidada(0,'test');estado.idadesAdultosColonia.splice(0,1);estado.populacaoColonia=0;atualizarCadastroCidada(true)");
  assert.equal(g.estado.economiaCidada.custodia,before.carteiras);assert.equal(g.estado.economiaCidada.creditosCustodia,before.atrasados);assert.equal(g.eval('auditoriaCidada().atrasados'),before.atrasados);conserved(g);
});
test('malformed next-ID counters cannot overwrite an existing person',()=>{
  const g=fixture();const before=Object.keys(g.estado.economiaCidada.pessoas);g.eval('estado.economiaCidada.proximoId=Number.MAX_SAFE_INTEGER;criarPessoaCidada("test")');
  const after=Object.keys(g.estado.economiaCidada.pessoas);assert.equal(after.length,before.length+1);assert.ok(after.every(id=>/^cid-[1-9]\d{0,8}$/.test(id)));assert.ok(before.every(id=>after.includes(id)));
});
console.log('CITIZEN_ECONOMY_OK '+groups+' groups');
